apiVersion: v1
kind: Pod
metadata:
  name: sample-node-service-pod
  labels:
    release: beta
    type: poc
spec:
  containers:
    - name: sample-node-service-container
      image: myproject/sample-node-service
      ports:
        - containerPort: 8081
